apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3-minio-tithia-scio-services
  namespace: minio
spec:
  secretName: s3-minio-tithia-scio-services-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: "s3.minio.tithia.scio.services"
  dnsNames:
  - "s3.minio.tithia.scio.services"