apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ui
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
  - host: minio.tithia.scio.services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-ui
            port:
              number: 9090
  tls:
  - hosts:
    - minio.tithia.scio.services
    secretName: minio-tithia-scio-services-tls