apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio
type: Opaque
data:
  MINIO_ROOT_USER: ZnlzYWxpZGE=   # "fysalida" base64-encoded
  MINIO_ROOT_PASSWORD: a3gxMmt4MTI= # "kx12kx12" base64-encoded
