apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db
type: Opaque
data:
  POSTGRES_DB: bXlkYXRhYmFzZQ==      # base64 for 'mydatabase'
  POSTGRES_USER: bXl1c2Vy            # base64 for 'myuser'
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== # base64 for 'mypassword'
