apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db
type: Opaque
data:
  POSTGRES_DB: bXlkYXRhYmFzZQ==      # 'mydatabase'
  POSTGRES_USER: bXl1c2Vy            # 'myuser'
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== # 'mypassword'
