services:
  sedona-notebook:
    build:
      context: .
    container_name: sedona-notebook
    network_mode: host
    volumes:
      - ../sedona_examples:/home/jovyan/sedona_examples
    ports:
      - 8888:8888
