services:
  spark-notebook:
    build:
      context: .
    container_name: spark-notebook
    network_mode: host
    volumes:
      - ../spark_examples:/home/jovyan/work
    ports:
      - 8888:8888
