apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: spark
spec:
  selector:
    app: spark
    role: master
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
      name: spark
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
  type: ClusterIP