apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-providers-pvc
  namespace: keycloak
  labels:
    pvc: keycloak-providers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
