apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  KC_PROXY_HEADERS: Zm9yd2FyZGVk # forwarded
  KC_DB: cG9zdGdyZXM= # postgres
  KC_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMuZGIuc3ZjLmNsdXN0ZXIubG9jYWwva2V5Y2xvYWs/dXNlcj1teXVzZXImcGFzc3dvcmQ9bXlwYXNzd29yZA== # jdbc:postgresql://postgres.db.svc.cluster.local/keycloak?user=myuser&password=mypassword
  KEYCLOAK_ADMIN: YWRtaW4= # admin
  KEYCLOAK_ADMIN_PASSWORD: cGFzc3dvcmQ= # password
  KC_HOSTNAME: aHR0cHM6Ly9hdXRoLnRpdGhpYS5zY2lvLnNlcnZpY2VzLw== # https://auth.tithia.scio.services/
  KC_HTTPS_CERTIFICATE_FILE: L2V0Yy9jZXJ0cy90bHMuY3J0 # /etc/certs/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: L2V0Yy9jZXJ0cy90bHMua2V5 # /etc/certs/tls.key
