name: Build and Push Tithia Spark Docker Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tithia-spark-docker-build.yml'
      - 'docker/tithia-spark/**'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/tithia-spark
          file: ./docker/tithia-spark/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-spark:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-spark:3.5.2-0.${{ github.run_number }}
